CREATE DATABASE IF NOT EXISTS quizdb;
USE quizdb;
CREATE TABLE IF NOT EXISTS scores (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255),
 email VARCHAR(255),
 q1 INT, q2 INT, q3 INT, q4 INT, q5 INT,
 total INT
);